# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dictionary.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'dictionary.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x64ictionary.proto\x12\ndictionary\"(\n\x04Term\x12\x0c\n\x04term\x18\x01 \x01(\t\x12\x12\n\ndefinition\x18\x02 \x01(\t\"7\n\x0e\x41\x64\x64TermRequest\x12%\n\x0bterm_to_add\x18\x01 \x01(\x0b\x32\x10.dictionary.Term\"3\n\x0f\x41\x64\x64TermResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1e\n\x0eGetTermRequest\x12\x0c\n\x04term\x18\x01 \x01(\t\"\x14\n\x12GetAllTermsRequest\"6\n\x13GetAllTermsResponse\x12\x1f\n\x05terms\x18\x01 \x03(\x0b\x32\x10.dictionary.Term\"S\n\x11UpdateTermRequest\x12\x15\n\roriginal_term\x18\x01 \x01(\t\x12\'\n\rnew_term_data\x18\x02 \x01(\x0b\x32\x10.dictionary.Term\"6\n\x12UpdateTermResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"!\n\x11\x44\x65leteTermRequest\x12\x0c\n\x04term\x18\x01 \x01(\t\"6\n\x12\x44\x65leteTermResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xf3\x02\n\nDictionary\x12\x42\n\x07\x41\x64\x64Term\x12\x1a.dictionary.AddTermRequest\x1a\x1b.dictionary.AddTermResponse\x12\x37\n\x07GetTerm\x12\x1a.dictionary.GetTermRequest\x1a\x10.dictionary.Term\x12N\n\x0bGetAllTerms\x12\x1e.dictionary.GetAllTermsRequest\x1a\x1f.dictionary.GetAllTermsResponse\x12K\n\nUpdateTerm\x12\x1d.dictionary.UpdateTermRequest\x1a\x1e.dictionary.UpdateTermResponse\x12K\n\nDeleteTerm\x12\x1d.dictionary.DeleteTermRequest\x1a\x1e.dictionary.DeleteTermResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dictionary_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TERM']._serialized_start=32
  _globals['_TERM']._serialized_end=72
  _globals['_ADDTERMREQUEST']._serialized_start=74
  _globals['_ADDTERMREQUEST']._serialized_end=129
  _globals['_ADDTERMRESPONSE']._serialized_start=131
  _globals['_ADDTERMRESPONSE']._serialized_end=182
  _globals['_GETTERMREQUEST']._serialized_start=184
  _globals['_GETTERMREQUEST']._serialized_end=214
  _globals['_GETALLTERMSREQUEST']._serialized_start=216
  _globals['_GETALLTERMSREQUEST']._serialized_end=236
  _globals['_GETALLTERMSRESPONSE']._serialized_start=238
  _globals['_GETALLTERMSRESPONSE']._serialized_end=292
  _globals['_UPDATETERMREQUEST']._serialized_start=294
  _globals['_UPDATETERMREQUEST']._serialized_end=377
  _globals['_UPDATETERMRESPONSE']._serialized_start=379
  _globals['_UPDATETERMRESPONSE']._serialized_end=433
  _globals['_DELETETERMREQUEST']._serialized_start=435
  _globals['_DELETETERMREQUEST']._serialized_end=468
  _globals['_DELETETERMRESPONSE']._serialized_start=470
  _globals['_DELETETERMRESPONSE']._serialized_end=524
  _globals['_DICTIONARY']._serialized_start=527
  _globals['_DICTIONARY']._serialized_end=898
# @@protoc_insertion_point(module_scope)
